# Actions example

name: Deploy docs

on:
  push:
    branches:
      - main # or [main]

#
# defaults:
#   run:
#     working-directory: './design-system'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # setting up dependency caching
          cache-dependency-path: '**/package-lock.json' # wild card to find any lock

      - run: npm ci # ci version for npm install
      - run: npm run build
        env:
          TURBO_TOKEN: your-token
          TURBO_TEAM: your-team/account-name

      - name: Deploy storybook
        working-directory: './packages/docs'
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static # "run" related to the "name" = without "-"
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
