export const products = [
  {
    id: '22e19a32-246a-4765-bc6b-57af7954b2d8',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    imageUrl: '/tradicional.svg',
    price: 990,
    tags: ['tradicional'],
  },
  {
    id: '8239e226-aeb5-4ec4-8135-ea811fa2b829',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    imageUrl: '/americano.svg',
    price: 990,
    tags: ['tradicional'],
  },
  {
    id: '9538f4d0-0555-4617-bd47-b85af5586511',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    imageUrl: '/cremoso.svg',
    price: 990,
    tags: ['tradicional'],
  },
  {
    id: '3752f150-2ed3-4c03-a37f-1144c5c3b17d',
    name: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    imageUrl: '/com-leite.svg',
    price: 990,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: 'a02a73c3-df45-4490-9855-280ac7751f43',
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    imageUrl: '/latte.svg',
    price: 990,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: 'c09a72c4-bad7-4541-a0a7-2bb074580c66',
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    imageUrl: '/capuccino.svg',
    price: 990,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '9a8cb8bf-e50c-488b-9d96-0f8629be1631',
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    imageUrl: '/macchiato.svg',
    price: 990,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '4c57e1e6-7e28-4c27-8adb-d16ba7fbde3d',
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    imageUrl: '/mochaccino.svg',
    price: 990,
    tags: ['tradicional', 'com leite'],
  },
  {
    id: '2c5056a7-5390-4e75-bebb-db33c19ca618',
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    imageUrl: '/chocolate-quente.svg',
    price: 990,
    tags: ['especial', 'com leite'],
  },
  {
    id: 'dab8a5ca-aa11-4e7e-bff9-03f82ed6a8d1',
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    imageUrl: '/cubano.svg',
    price: 990,
    tags: ['especial', 'alcoólico', 'gelado'],
  },
  {
    id: '1132c8b0-7d7d-4895-9f40-9d10a4cee959',
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    imageUrl: '/havaiano.svg',
    price: 990,
    tags: ['especial'],
  },
  {
    id: 'c8d64a37-c5c1-4047-8b8f-331e8dd26d17',
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    imageUrl: '/arabe.svg',
    price: 990,
    tags: ['especial'],
  },
  {
    id: 'c8d637-c5c1-4047-8b8f-331e8dd26d17',
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    imageUrl: '/irlandes.svg',
    price: 990,
    tags: ['especial', 'alcoólico'],
  },
]
