name: Deploy docs

on:
  push:
    branches:
      - main # or [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: './design-system'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # setting up dependency caching
          cache-dependency-path: './design-system/**/package-lock.json' # wild card to find any lock

      - name: Install dependencies
        working-directory: './design-system'
        run: npm ci # ci version for npm install

      - name: Build project
        working-directory: './design-system'
        run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          TURBO_TEAM: nyyu

      - name: Deploy storybook
        working-directory: './design-system/packages/docs'
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static # "run" related to the "name" = without "-"
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
